/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jlox;

class AppTest {
    // @Test void appHasAGreeting() {
    //     Lox classUnderTest = new Lox();
    //     assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    // }
}
